### ISSUE TITLE
training_run() hangs when the R script is in a large folder

### ISSUE THREAD

**Issue by terrytangyuan** [rstudio/tfruns#9]
The two scripts are the same. One of them is placed in a folder with all other cloned git repositories, which is pretty large. The `training_run()` execution hangs without any progress being printed out. I am wondering whether it's trying to copy the whole folder anywhere in the code.

**Comment by jjallaire** [comment]
We do a recursive listing of .R files within the run directory so that is probably where the time is going. Could you try running with profvis to confirm that though?

We could only look for .R files in the root directory although there might be some corner cases where we miss helper files (but perhaps that's worth it to avoid the corner case you found).

**Comment by terrytangyuan** [comment]
Yeah tried that but it's been hanging there like forever.

**Comment by jjallaire** [comment]
Okay, I just committed a change to prevent the recursive listing. Could you try again with this change?

**Comment by terrytangyuan** [comment]
That fixed it! Thanks!
